routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index' );

Route::get('/dashboard', 'HomeController@index' )->name('home');

Auth::routes();



Route::resource('/projects', 'ProjectController');

// Task
Route::resource('/tasks', 'TaskController');
Route::get('/task-project/{slug}', 'TaskController@ProjectTask')->name('showTasks');
Route::post('/getTask', 'TaskController@GetTask');
Route::post('/addCommentTask', 'TaskController@AddCommentTask')->name('tasks.addComment');
Route::post('/deleteComment', 'TaskController@DeleteComment');
Route::post('/updateTask', 'TaskController@UpdateTask');
Route::post('/deleteTask', 'TaskController@DeleteTask');
Route::post('/getUserInfo', 'UserController@GetInfo');

app/Project.php
<?php

namespace HakaAdmin;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['photo','name', 'client_id', 'startDate', 'endDate','priority', 'leader_id', 'description'];

    public function tasks(){
        return $this->hasMany(Task::class);
    }

    public function pendingTasks(){
        return $this->hasMany(Task::class)->where('completed',0);
    }

    public function completeTasks(){
        return $this->hasMany(Task::class)->where('completed',1);
    }

    public function progress(){
        
        $completeTasks = $this->hasMany(Task::class)->where('completed',1)->get()->count();
        $totalTasks = $this->hasMany(Task::class)->get()->count();

        $progressProject = round(($completeTasks/$totalTasks) * 100);
        
        return $progressProject;
    }

    public function lider(){
    	return $this->belongsTo(User::class, 'leader_id');
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace HakaAdmin\Http\Controllers;
use Illuminate\Http\Request;

use HakaAdmin\Project;
use HakaAdmin\Client;
use HakaAdmin\User;
use HakaAdmin\Task;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $clients = Client::all();
        $users = User::all();
        $projects = Project::all();


        return view('projects.projects', compact('projects','clients','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nameFile = "";

        if($request->hasFile('photo')){
            $file = $request->file('photo');
            $nameFile = time().$file->getClientOriginalName();
            $file->move(public_path().'/images/projects/',$nameFile);
        }

        $project = new Project($request->except('team','photo'));
        $project->photo = $nameFile;
        $newSlug = str_replace(" ", "-", $request->name);
        $project->slug = strtolower($newSlug)."-".$project->id;
        $project->save();

        foreach ($request->team as $key => $value) {
            $project->users()->attach($value);
        }

        return  redirect()->route('projects.index')->with('status', 'Proyecto registrado exitosamente!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \HakaAdmin\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $project = Project::where('slug', $slug)->firstOrFail();
        $tasks = $project->tasks;
        $completeTasks = Task::where('completed', '1')->get()->count();
        $incompleteTasks = Task::where('completed', '1')->get()->count();

        if($tasks->count()  > 0)
            $progressProject = round(($completeTasks/$tasks->count()) * 100);
        else
            $progressProject = 0;

        $to = \Carbon\Carbon::createFromFormat('Y-m-d H:s:i',  $project->startDate.' 3:30:34');
        $from = \Carbon\Carbon::createFromFormat('Y-m-d H:s:i', $project->endDate.' 9:30:34');
        $today = \Carbon\Carbon::now();

        $totalHours = $to->diffInHours($from);
        $leftHours = $today->diffInHours($from);

        return view('projects.show', compact(
            'project',
            'completeTasks',
            'incompleteTasks',
            'tasks',
            'progressProject',
            'totalHours',
            'leftHours'
        ));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \HakaAdmin\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \HakaAdmin\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \HakaAdmin\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/projects/create.blade.php
<div id="create_project" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="modal-content modal-lg">
            <div class="modal-header">
                <h4 class="modal-title">Crear Proyecto</h4>
            </div>
            <div class="modal-body">
                <form action="{{ route('projects.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="white-box">
                                <label>Foto del Proyecto</label>
                                <input name="photo" type="file" id="input-file-now-custom-1" class="dropify" data-default-file="{{ asset('images/logo2.jpg') }}" />
                            </div>
                        </div>
                    </div>
                    <div class="white-box">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Nombre</label>
                                    <input type="text" id="email" class="input-form" name="name" required>
                                    <p class="helper helper1">Nombre del proyecto</p>
                                    <span class="indicator"></span>
                                </div>    
                            </div>
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Cliente</label>
                                    <select name="client" class="select input-form">
                                        <option value=""></option>
                                        @foreach ($clients as $client)
                                            <option value="{{ $client->id }}">{{$client->name}}</option>
                                        @endforeach
                                      
                                    </select>
                                    <p class="helper helper1">Cliente</p>
                                    <span class="indicator"></span>
                                </div>   
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Inicio</label>
                                    <input name="startDate" class="input-form datetimepicker" type="text" required>
                                    <p class="helper helper1">Fecha de Inicio</p>
                                    <span class="indicator"></span>
                                </div>    
                            </div>
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Final</label>
                                    <input name="endDate" class="input-form datetimepicker" type="text" required>
                                    <p class="helper helper1">Fecha de Entrega</p>
                                    <span class="indicator"></span>
                                </div>    
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Prioridad</label>
                                    <select name="priority" class="select input-form" required>
                                        <option></option>
                                        <option>Baja</option>
                                        <option>Media</option>
                                        <option>Alta</option>
                                    </select>
                                    <p class="helper helper1">Prioridad</p>
                                    <span class="indicator"></span>
                                </div>
                            </div>   
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Lider</label>
                                    <select name="leader_id" class="select input-form" required>
                                        <option></option>
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{$user->username}}</option>
                                        @endforeach
                                    </select>
                                    <p class="helper helper1">Lider del Proyecto</p>
                                    <span class="indicator"></span>
                                </div>   
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="inputGroup inputGroup1">
                                    <label>Equipo</label>
                                    <select id="team" class="js-example-basic-multiple select input-form" name="team[]" multiple="multiple" required>
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{$user->username}}</option>
                                        @endforeach
                                    </select>
                                </div>   
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Miembros del Equipo </label>
                                    <div id="teamContent" class="project-members">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="inputGroup inputGroup1">
                                <label>Descripción</label>
                                <textarea style="padding: 22px 1em 0px;" name="description" rows="4" cols="5" class="input-form summernote"></textarea>
                                <span class="indicator"></span>
                            </div>   
                        </div>
                    </div>
                    <div class="white-box">
                        <div class="m-t-20 text-center">
                            <button class="button-haka">Crear Proyecto</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/projects/projects.blade.php
@extends('layouts.admin')

@section('title', 'Proyectos')

@section('css')
    <link href="{{ asset('plugins/bower_components/register-steps/steps.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="../plugins/bower_components/clockpicker/dist/jquery-clockpicker.min.css" rel="stylesheet">
    <link href="../plugins/bower_components/jquery-asColorPicker-master/dist/css/asColorPicker.css" rel="stylesheet">
    <link href="../plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="../plugins/bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <link href="plugins/summernote/dist/summernote.css" rel="stylesheet">
    <link href="../plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="../plugins/bower_components/custom-select/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="../plugins/bower_components/switchery/dist/switchery.min.css" rel="stylesheet" />
    <link href="../plugins/bower_components/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
    <link href="../plugins/bower_components/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" rel="stylesheet" />
    <link href="../plugins/bower_components/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css" rel="stylesheet" />
    <link href="../plugins/bower_components/multiselect/css/multi-select.css" rel="stylesheet" type="text/css" />

@endsection

@section('content')

<div class="row">
    <div class="col-xs-4">
        <h4 class="page-title">Proyectos</h4>
    </div>
    <div class="col-xs-8 text-right m-b-30">
        <a href="#" class="btn btn-primary rounded pull-right" data-toggle="modal" data-target="#create_project"><i class="fa fa-plus"></i> Crear Proyecto</a>
        <div class="view-icons">
            <a href="{{ route('projects.index') }}" class="grid-view btn btn-link active"><i class="fa fa-th"></i></a>
            <a href="#" class="list-view btn btn-link"><i class="fa fa-bars"></i></a>
        </div>
    </div>
</div>
@include('commons.alert')
@foreach ($projects as $project)
    <div class="col-lg-3 col-sm-4">
        <div class="card-box project-box">
            <div class="dropdown profile-action">
                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                <ul class="dropdown-menu pull-right">
                    <li><a href="/task-project/{{$project->slug}}"><i class="fa fa-pencil m-r-5"></i> Tareas</a></li>
                    <li><a href="#" data-toggle="modal" data-target="#edit_project"><i class="fa fa-pencil m-r-5"></i> Editar</a></li>
                    <li><a href="#" data-toggle="modal" data-target="#delete_project"><i class="fa fa-trash-o m-r-5"></i> Eliminar</a></li>
                </ul>
            </div>
            <h4 class="project-title"><a href="/projects/{{ $project->slug }}">{{ $project->name }}</a></h4>
            <img src="{{ asset( 'images/projects/'.$project->photo ) }}" height="192" width="192" center="">
            <small class="block text-ellipsis m-b-15">
                <span class="text-xs">{{ count($project->pendingTasks) }}</span> <span class="text-muted">Tareas Abiertas, </span>
                <span class="text-xs">{{ count($project->completeTasks) }}</span> <span class="text-muted">Tareas Completadas</span>
            </small>
            <p class="text-muted">{!! str_limit( $project->description, 256)  !!}
            </p>
            <div class="pro-deadline m-b-15">
                <div class="sub-title">
                    Fecha de Entrega:
                </div>
                <div class="text-muted">
                    {{ $project->endDate }}
                </div>
            </div>
            <div class="project-members m-b-15">
                <div>Lider del Proyecto:</div>
                <ul class="team-members">
                    <li>
                        <a href="#" data-toggle="tooltip" title="{{$project->lider->username}}"><img src="{{asset('/images/users/'.$project->lider->photo)}}" alt="{{ $project->lider_id }}"></a>
                    </li>
                </ul>
            </div>
            <div class="project-members m-b-15">
                <div>Equipo :</div>
                <ul class="team-members">
                    @foreach ($project->users as $user)
                        <li>
                            <a href="#" data-toggle="tooltip" title="{{ $user->username}}">
                                <img src="{{asset('/images/users/'.$user->photo)}}" alt="{{$user->username}}">
                            </a>
                        </li>
                    @endforeach
                </ul>
            </div>
            <p class="m-b-5">Progreso <span class="text-success pull-right">{{count($project->tasks) > 0 ? $project->progress() : 0}}%</span></p>
            <div class="progress progress-xs m-b-0">
                <div class="progress-bar progress-bar-success" role="progressbar" data-toggle="tooltip" title="40%" style="width: {{count($project->tasks) > 0 ? $project->progress() : 0}}%"></div>
            </div>
        </div>
    </div>
@endforeach

@include('projects.create')
@endsection

@section('scripts')
    <script type="text/javascript" src="/js/moment.min.js"></script>
    <script type="text/javascript" src="/js/select2.min.js"></script>
    <script type="text/javascript" src="js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="plugins/summernote/dist/summernote.min.js"></script>
    <script>
            $(document).ready(function(){
                $('.summernote').summernote({
                    height: 200,                 // set editor height
                    minHeight: null,             // set minimum height of editor
                    maxHeight: null,             // set maximum height of editor
                    focus: false                 // set focus to editable area after initializing summernote
                });
                $('#team').change(function(){
                    var token = $('#csrf-token-id').attr('content');
                    var team = $(this).val();
                    $.ajax({
                        url: '/getUserInfo',
                        headers: {'X-CSRF-TOKEN': token},
                        type: 'POST',
                        dataType: 'json',
                        async: true,
                        data: { 
                            'team': team,
                        },
                        success: function(response){
                            if(response.status == true){
                                $('#teamContent').empty();
                                $.each(response.users, function(index,user){
                                    $('#teamContent').append(
                                        '<a href="/profile/'+user.id+'" data-toggle="tooltip" title="'+user.username+'">'+
                                        '<img src="/images/users/'+user.photo+'" class="avatar" alt="'+user.username+'" height="20" width="20">'+
                                        '</a>'
                                    )
                                });
                            }
                        }
                    });
                });

            });
    </script>
    <script>
        $( document ).ready(function() {
            $('.js-example-basic-multiple').select2();
            $('.datetimepicker').datetimepicker({
                format: 'YYYY/MM/DD'
            });
            $(".input-form").focus(function(){
                $(this).parent().addClass("focusWithText");
            });

            $( ".input-form" ).blur(function() {
                if($(this).val() == "")
                    $(this).parent().removeClass("focusWithText");
            });
        });
    </script>
    <!-- jQuery file upload -->
    <script src="../plugins/bower_components/dropify/dist/js/dropify.min.js"></script>
    <script>
    $(document).ready(function() {
        // Basic
        $('.dropify').dropify();
        // Translated
        $('.dropify-fr').dropify({
            messages: {
                default: 'Glissez-déposez un fichier ici ou cliquez',
                replace: 'Glissez-déposez un fichier ou cliquez pour remplacer',
                remove: 'Supprimer',
                error: 'Désolé, le fichier trop volumineux'
            }
        });
        // Used events
        var drEvent = $('#input-file-events').dropify();
        drEvent.on('dropify.beforeClear', function(event, element) {
            return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
        });
        drEvent.on('dropify.afterClear', function(event, element) {
            alert('File deleted');
        });
        drEvent.on('dropify.errors', function(event, element) {
            console.log('Has Errors');
        });
        var drDestroy = $('#input-file-to-destroy').dropify();
        drDestroy = drDestroy.data('dropify')
        $('#toggleDropify').on('click', function(e) {
            e.preventDefault();
            if (drDestroy.isDropified()) {
                drDestroy.destroy();
            } else {
                drDestroy.init();
            }
        })
    });
    </script>

    <script src="../plugins/bower_components/moment/moment.js"></script>
    <!-- Clock Plugin JavaScript -->
    <script src="../plugins/bower_components/clockpicker/dist/jquery-clockpicker.min.js"></script>
    <!-- Color Picker Plugin JavaScript -->
    <script src="../plugins/bower_components/jquery-asColor/dist/jquery-asColor.js"></script>
    <script src="../plugins/bower_components/jquery-asGradient/dist/jquery-asGradient.js"></script>
    <script src="../plugins/bower_components/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script>
    <!-- Date Picker Plugin JavaScript -->
    <script src="../plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="../plugins/bower_components/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="../plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script>
    // Clock pickers
    $('#single-input').clockpicker({
        placement: 'bottom',
        align: 'left',
        autoclose: true,
        'default': 'now'
    });
    $('.clockpicker').clockpicker({
        donetext: 'Done',
    }).find('input').change(function() {
        console.log(this.value);
    });
    $('#check-minutes').click(function(e) {
        // Have to stop propagation here
        e.stopPropagation();
        input.clockpicker('show').clockpicker('toggleView', 'minutes');
    });
    if (/mobile/i.test(navigator.userAgent)) {
        $('input').prop('readOnly', true);
    }
    // Colorpicker
    $(".colorpicker").asColorPicker();
    $(".complex-colorpicker").asColorPicker({
        mode: 'complex'
    });
    $(".gradient-colorpicker").asColorPicker({
        mode: 'gradient'
    });
    // Date Picker
    jQuery('.mydatepicker, #datepicker').datepicker();
    jQuery('#datepicker-autoclose').datepicker({
        autoclose: true,
        todayHighlight: true
    });
    jQuery('#date-range').datepicker({
        toggleActive: true
    });
    jQuery('#datepicker-inline').datepicker({
        todayHighlight: true
    });
    // Daterange picker
    $('.input-daterange-datepicker').daterangepicker({
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse'
    });
    $('.input-daterange-timepicker').daterangepicker({
        timePicker: true,
        format: 'MM/DD/YYYY h:mm A',
        timePickerIncrement: 30,
        timePicker12Hour: true,
        timePickerSeconds: false,
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse'
    });
    $('.input-limit-datepicker').daterangepicker({
        format: 'MM/DD/YYYY',
        minDate: '06/01/2015',
        maxDate: '06/30/2015',
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse',
        dateLimit: {
            days: 6
        }
    });
    </script>
@endsection