routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index' );

Route::get('/dashboard', 'HomeController@index' )->name('home');

Auth::routes();



Route::resource('/projects', 'ProjectController');

// Task
Route::resource('/tasks', 'TaskController');
Route::get('/task-project/{slug}', 'TaskController@ProjectTask')->name('showTasks');
Route::post('/getTask', 'TaskController@GetTask');
Route::post('/addCommentTask', 'TaskController@AddCommentTask')->name('tasks.addComment');
Route::post('/deleteComment', 'TaskController@DeleteComment');
Route::post('/updateTask', 'TaskController@UpdateTask');
Route::post('/deleteTask', 'TaskController@DeleteTask');
Route::post('/getUserInfo', 'UserController@GetInfo');

app/Task.php
<?php

namespace HakaAdmin;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'name',
        'user_id',
        'project_id',
        'startDate',
        'endDate',
        'priority',
        'description'
    ];

    public function project(){
    	return $this->belongsTo(Project::class);
    }
    public function user(){
    	return $this->belongsTo(User::class);
    }

    public function comments(){
    	return $this->belongsToMany(Comment::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace HakaAdmin\Http\Controllers;

use HakaAdmin\Task;
use HakaAdmin\Project;
use HakaAdmin\Client;
use HakaAdmin\User;
use HakaAdmin\Comment;


use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $isTask = true;
        $projects = Project::all();
        $clients = Client::all();
        $users = User::all();
        $tasks = Task::all();

        return view('tasks.indexTask', compact('projects','clients','users','isTask','tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newTask = new Task($request->all());
        $newTask->save();

        if($request->ajax()){
            return response()->json([
                'status' => true,
                'task' => $newTask,
                'user' => $newTask->user
            ]);
        }
    }

    public function GetTask(Request $request){
        $task = Task::where('id',$request->task_id)->with('user','comments','comments.user')->first();
        if($request->ajax()){
            return response()->json([
                'status' => true,
                'task' => $task,
            ]);
        }
    }

    public function DeleteComment(Request $request){
        $comment = Comment::find($request->comment_id);
        $comment->delete();

        if($request->ajax()){
            return response()->json([
                'status' => true
            ]);
        }
    }

    public function UpdateTask(Request $request){
        $task = Task::find($request->task_id);
        $task->name = $request->name;
        $task->porcentage = $request->porcentage;
        $task->completed = $request->completed;

        $task->save();

        if($request->ajax()){
            return response()->json([
                'status' => true
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \HakaAdmin\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    public function AddCommentTask(Request $request)
    {
        $task = Task::find($request->task_id);
        $comment = Comment::create($request->except('task_id'));
        $task->comments()->attach($comment->id);

        if($request->ajax()){
            return response()->json([
                'status' => true,
                'comment' => $comment,
                'user' => $comment->user
            ]);
        }
    }

    

    public function ProjectTask($slug)
    {
        $project = Project::where('slug', $slug)->firstOrFail();
        $isTask = true;
        $projects = Project::all();
        $clients = Client::all();
        $users = User::all();
        $tasks = $project->tasks;

        return view('tasks.task', compact('projects','clients','users','isTask','tasks','project'));
    }

    public function DeleteTask(Request $request)
    {
        $task = Task::find($request->task_id);
        $task->delete();

        if($request->ajax()){
            return response()->json([
                'status' => true
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \HakaAdmin\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \HakaAdmin\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \HakaAdmin\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
}

resources/views/tasks/create.blade.php
@section('css')
    <link href="{{ asset('plugins/bower_components/register-steps/steps.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="../plugins/bower_components/clockpicker/dist/jquery-clockpicker.min.css" rel="stylesheet">
    <link href="../plugins/bower_components/jquery-asColorPicker-master/dist/css/asColorPicker.css" rel="stylesheet">
    <link href="../plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="../plugins/bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <link href="plugins/summernote/dist/summernote.css" rel="stylesheet">
@endsection

<div id="create_task" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="modal-content modal-lg">
            <div class="modal-header">
                <h4 class="modal-title">Crear Tarea</h4>
            </div>
            <div class="modal-body">
                <div class="form new-task-wrapper">
                    <form id="formTask" action="{{ route('tasks.store') }}" method="post" enctype="multipart/form-data" >
                        @csrf
                        <input type="hidden" name="project_id" value="{{ $project->id }}">
                        <div class="white-box">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="inputGroup inputGroup1">
                                        <label>Nombre</label>
                                        <input id="new-task" type="text" class="input-form" name="name" required>
                                        <span class="error-message hidden">Debes ingresar asignar un nombre a la tarea</span>
                                        <p class="helper helper1">Nombre de la tarea</p>
                                        <span class="indicator"></span>
                                    </div>    
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="inputGroup inputGroup1">
                                        <label>Inicio</label>
                                        <input id="startDate" name="startDate" class="input-form datetimepicker" required>
                                        <p class="helper helper1">Fecha de Inicio</p>
                                        <span class="indicator"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="inputGroup inputGroup1">
                                        <label>Final</label>
                                        <input id="endDate" name="endDate" class="input-form datetimepicker" required>
                                        <p class="helper helper1">Fecha de Entrega</p>
                                        <span class="indicator"></span>
                                    </div>    
                                </div>
                                <div class="col-md-3">
                                    <div class="inputGroup inputGroup1">
                                        <label>Prioridad</label>
                                        <select id="priority" name="priority" class="select input-form">
                                            <option></option>
                                            <option>Baja</option>
                                            <option>Media</option>
                                            <option>Alta</option>
                                        </select>
                                        <p class="helper helper1">Prioridad</p>
                                        <span class="indicator"></span>
                                    </div>
                                </div> 
                                <div class="col-md-3">
                                    <div class="inputGroup inputGroup1">
                                        <label>Asignar</label>
                                        <select name="user_id" class="select input-form" required>
                                            <option></option>
                                            @foreach ($users as $user)
                                                <option value="{{ $user->id }}">{{$user->username}}</option>
                                            @endforeach
                                        </select>
                                        <p class="helper helper1">Asignar Usuario</p>
                                        <span class="indicator"></span>
                                    </div>   
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="inputGroup inputGroup1">
                                            <label>Descripción</label>
                                            <textarea id="description" style="padding: 22px 1em 0px;" name="description" rows="4" cols="5" class="input-form summernote"></textarea>
                                            <span class="indicator"></span>
                                        </div>   
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="white-box">
                            <div class="m-t-20 text-center">
                                    {{--  data-dismiss="modal"  --}}
                                <button type="submit" id="add-task" class="button-haka add-new-task-btn" >Crear Tarea</button>
                            </div>
                        </div>
                    </form>
                </div>
               
                </div>
            </div>
        </div>
    </div>
</div>
    

resources/views/tasks/details.blade.php
<div id="taskDetails" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="modal-content modal-lg">
            <div class="modal-header">
                <h4  class="modal-title nameTaskDetail"></h4>
            </div>
            <div class="modal-body">
                <div id="taskContentDetail" class="form new-task-wrapper">
                    <input type="hidden" name="project_id" value="{{ $project->id }}">
                    <div class="white-box">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Nombre de la tarea</p>
                                        <p class="text nameTaskDetail"></p>
                                    </div>    
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Inicio</p>
                                        <p id="startDateDetail" class="text"></p>
                                    </div>  
                                </div>
                                <div class="col-md-3">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Final</p>
                                        <p id="endDateDetail" class="text"></p>
                                    </div>  
                                </div>
                                <div class="col-md-3">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Asignado</p>
                                        <p id="assignedDetail" class="text"></p>
                                    </div>  
                                </div>
                                <div class="col-md-3">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Prioridad <i class="far fa-dot-circle text-danger"></i></p>
                                        <p id="priorityDetail" class="text"> </p>
                                    </div>  
                                </div> 
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="detail focusWithText">
                                        <p class="helper helper1">Descripción</p>
                                        <div id="descriptionDetail" class="text"></div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="white-box">
                        <div class="panel-body">
                            <h5 class="panel-title m-b-20">Imagenes Subidas</h5>
                            <div class="row">
                                <div class="col-md-3 col-sm-6">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img src="{{asset('images/logo2.jpg')}}" class="img-responsive" alt="">
                                        </div>
                                        <div class="caption text-center">
                                                demo.png
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img src="{{asset('images/logo2.jpg')}}" class="img-responsive" alt="">
                                        </div>
                                        <div class="caption text-center">
                                                demo.png
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img src="{{asset('images/logo2.jpg')}}" class="img-responsive" alt="">
                                        </div>
                                        <div class="caption text-center">
                                                demo.png
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-6">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img src="{{asset('images/logo2.jpg')}}" class="img-responsive" alt="">
                                        </div>
                                        <div class="caption text-center">
                                                demo.png
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="white-box">
                        <div class="panel-body">
                            <h5 class="panel-title m-b-20">Comentarios</h5>
                        </div>
                    </div>
                        
                    {{--  <div class="white-box">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="comment focusWithText">
                                    <div>
                                        <img class="img-comment" title="JuanJO" src="http://hakaadmin.loc/images/users/1568443486s-l300.jpg" class="img-circle cursor-pointer" width="30">
                                        <a href="#"><p class="user-comment">JuanJO</p></a>
                                        <span class="comment-action-btn">
                                            <span class="action-circle large" title="Detalles">
                                                <i class="material-icons">edit</i>
                                            </span>
                                            <span class="action-circle large delete-btn" title="Borrar tarea">
                                                <i class="material-icons">delete</i>
                                            </span>
                                        </span>
                                        <span class="see-content">0
                                            <i class="fas fa-eye"></i>
                                        </span>
                                    </div>
                                    <p class="helper helper1"> Hace 4min</p>
                                    <div class="text">
                                        {!! $comment->description !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  --}}
                </div>
                <form id="formComment" action="{{ route('tasks.addComment') }}" method="post" enctype="multipart/form-data" >
                    <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                    <input type="hidden" name="task_id" id="taskID">
                    <div class="white-box">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="inputGroup inputGroup1">
                                        <label>Comentario</label>
                                        <textarea style="padding: 22px 1em 0px;" name="description" rows="4" cols="5" class="input-form summernote"></textarea>
                                        <span class="indicator"></span>
                                    </div>   
                                </div>
                            </div>
                        </div>
                        <div class="m-t-20 text-center">
                            <button type="submit" class="button-haka" >Agregar Comentario</button>
                        </div>
                    </div>
                </form>
                
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/tasks/taskMenu.blade.php
<!-- Left navbar-header -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3>
                <span class="fa-fw open-close">
                    <img style="width: 42px;" src="{{ asset('images/haka0.png') }}">
                </span> 
                <span class="hide-menu">
                    <img  style="width: 115px;margin-left: 35px;" src="{{ asset('images/haka1.png') }}">
                </span>
            </h3> 
        </div>
        <ul class="nav" id="side-menu">
            <li><a href="{{ route('home') }}"><i class="icon-dashboard"></i> <span class="hide-menu fix-menu">Regresar Dashboard</span></a></li>
            <li><a href="{{ route('tasks.index') }}" class="waves-effect"><i class="icon-task"></i><span class="hide-menu fix-menu">Tareas</span></a></li>
            <li >
                <a href="javascript:void(0)" class="waves-effect">
                    {{--  <i class="icon-project"></i>  --}}
                    <span class="menu-title hide-menu">Mis Proyectos
                        <span style="margin-top: 10px;" class="fa fa-plus pull-right" data-toggle="modal" data-target="#create_project"></span>
                    </span>
                </a>
                
            </li>
            @foreach ($projects as $key => $project)
                <li><a href="/task-project/{{$project->slug}}" class="waves-effect"><i class="icon-project" style="background: url(../../images/projects/{{$project->photo}}); background-repeat: no-repeat; background-size: 26px 26px;"></i></i><span class="hide-menu fix-menu">{{$project->name}}</span></a></li>
            @endforeach
            
        </ul>
    </div>
</div>
<!-- Left navbar-header end -->